[http]
listen = "0.0.0.0:8080"
cors_origins = []

[database]
host = "localhost"
port = 3306
# missing: username, password
db_name = "faktury"
prefer_socket = true
max_pool_size = 8

[accounts]
login_ttl = "2 days"
